pnpm_move update
mathjax/MathJax-src pull request #1023
Opened 2023-11-20 15:35 UTC by dpvc

This PR makes the changes that we discussed face-to-face:

* The `makeAll` script is modified to not cd to the component directories, but rather passes the directory to the various programs as their last argument.  This avoids the problem that you fixed in the `pack` command, in particular.

* The package scripts are modified:
    -  The `\e` escape is replaced by `\x1B` since MacOS ships with an older bash version that doesn't support that.
    - The color was changed from 32 (yellow) to 34 (blue) in `log:single`, and `--` was added to help make it visually distinct (especially when `log:comp` is used before it)`.
    - The `cjs` and `mjs` names were moved to the front of their commands to make the sections each use a prefix.
    - The mml3 XSLT commands were modified to use an `mml3:` prefix like the other sections
    - The cleaning of the `bundle-cjs` directory was moved earlier in the `clean` command so that the log messages are in a more appropriate order.

2023-11-22 15:56 UTC, zorkow reviewed
We could go one step further with our naming convention and do:
```
cjs:components:clean...
cjs:components:build...
...
cjs:bundle:clean ...
```

What do you think?

2023-11-22 16:19 UTC, zorkow requested changes
The `\x1B` change does not work for me. I'll look into it what we could use instead.

2023-11-22 16:19 UTC, zorkow commented on package.json
> +    "log:comp": "log() { echo \\\\x1B[32m$1\\x1B[0m\\; }; log",
Superfluous `\\;` leads to errors. 
```suggestion
    "log:comp": "log() { echo \\\\x1B[32m$1\\x1B[0m; }; log",
```

2023-11-22 16:25 UTC, zorkow commented
> The `\x1B` change does not work for me. I'll look into it what we could use instead.

@dpvc can you try this line, if the `\033` escape code works for you?

```
    "log:test": "log() { echo \\\\033[33m hello world \\\\033[0m; }; log",
```

[Source: Stackoverflow](https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences)

2023-11-22 18:21 UTC, dpvc commented
> We could go one step further with our naming convention

Sounds good.  Go ahead with that.

> can you try this line, if the \033 escape code works for you?

Yes, it does.  That was going to be my suggestion as well.

2023-11-23 15:24 UTC, zorkow approved these changes
Thanks. I'll go ahead and merge.

2023-11-23 15:24 UTC, merged