Move to scoped packages for fonts, and use woff2 format
mathjax/MathJax-src pull request #1168
Opened 2024-11-19 20:35 UTC by dpvc

This PR moves to using WOFF2 formatted fonts, and moves the font npm packages into the `@mathjax` scope.  I've already published the font packages in that scope.  A later step before beta.8 is release will be to move `mathjax-full` into the scoped package as well, which will require additional changes, both to the fonts and to MathJax source (`mathjax-full` will need to be replaced by `@mathjax/src`, for example).  That will be done in a separate PR later.

The `fontURL` and `dynamicPrefix` values in these files aren't actually used, as they are overridden by the fonts, which are subclasses of the `FontData` objects and provide their own value for these.

This PR also corrects the tsconfig files to point to `mathjax-newcm` rather than `mathjax-modern`, which were missed in the PR that swapped the default font.

2024-11-20 19:05 UTC, dpvc commented
I forgot to say that you need to use the `lab-woff2` branch in the MathJax-dev repository to test this.  Do a `ppm install` first to get the new versions of the fonts.

2025-01-14 16:14 UTC, zorkow requested changes
Finally tested it full. Works initially great in the lab. It also loads the font files for `newcm` correctly, e.g., `mjx-ncm-ds.woff2` and `mjx-ncm-c.woff2` for `mathbb` and `mathcal`, respectively. 

However, when I try to change the output font to, say, `asana` I get the following error:
```
Failed to fetch dynamically imported module: ￼http://localhost/MathJax/MathJax-dev/node_modules/@mathjax/mathjax-asana-font/chtml/woff2/chtml.js
```
* When changing the `fontURL` then I `newcm` does not load anymore on startup.
* When I copy the `chtml.js` from the toplevel of `mathjax-asana-font` to `woff2`, it works for the basic font, but fails for doublestruck and caligraphic, as it tries to find the sources at `woff2/chtml/dynamic` rather than `woff2/dynamic`
* When using the SVG renderer, I run into the same problem. 

Is there something wrong in my setup? Just in case, I installed and built everything from scratch.

2025-01-14 16:27 UTC, dpvc commented
It looks like a path is incorrectly set.  I'll look into it.

2025-01-14 20:39 UTC, dpvc commented
Ok, I've updated both the `lab-woff2` branch and the `woff2` branch in MathJax-src to fix these issues.  You will need to do `pnpm install` again when you get the new `lab-woff2` branch in order to get the mhchem font (for use with the `mhchem-stretchies` branch).

2025-02-07 22:27 UTC, zorkow approved these changes
lgtm.

2025-02-13 12:39 UTC, merged