Handle variant forms for pseudo-scripts better.  (mathjax/MathJax#2519)
mathjax/MathJax-src pull request #604
Opened 2021-03-02 16:03 UTC by dpvc

This PR improves the handling of pseudo scripts so that both the super-script version (using `msup`) and the non-superscript versions will render properly (with a font that has the proper glyphs available, like STIX2).  In the past, MathJax used the larger sized primes in the `normal` mathvariant, and this lead to incorrect sizes being used when the primes were not in `msup`.  This PR now expects the regular size to be in the `normal` variant and the larger size in the `-tex-variant` font, and the `mo` element sets the correct variant for the position it is used in.  It also remaps common characters that might be used for primes to their appropriate prime character (e.g., `'` maps to U+2032 (prime)).

That means `<msup><mi>x</mi><mo>'</mo></msup>`, `<mi>x</mi><mo>'</mo>` and `<mtext>x&#x2032</mtext>` will all render properly (when the font contains the right characters, which the MathJax TeX fonts don't, but the STIX2 fonts do).

This is intended as a step toward making MathJax work better with STIX2, as well as setting the stage for modifications to the MathJax fonts later this summer.

2021-03-19 15:15 UTC, zorkow requested changes
I remembered the discussion we had on that:
We wanted to handle pseudoprimes in `core` and giving the resulting node a `pseudoprime` property instead.
Firstly, we could expose the property (e.g., for SRE). And secondly, it would not need to be handled explicitly in the `Wrapper`.

2021-03-19 16:58 UTC, dpvc commented
Right you are!  Thanks for coming up with it again.  It had totally slipped my mind.

2021-03-19 21:57 UTC, dpvc commented
OK, I've moved the pseudo-script and prime checking to the `MmlMo` class and marked them with properties.  The pseudo-prime is exposed on the serialized MathML output for your convenience in SRE.

2021-03-29 12:07 UTC, zorkow approved these changes
Only some minor things.

2021-03-29 12:07 UTC, zorkow commented on ts/core/MmlTree/MmlNodes/mo.ts
> +    if (!mo.match(PRIMES)) return;
Swap lines 468 and 469.

2021-03-29 12:07 UTC, zorkow commented on ts/output/common/Wrappers/mo.ts
> +        chars = unicodeChars(primes);
Just have `return unicodeChars(primes);` here and save an `else`.

2021-03-29 12:07 UTC, zorkow commented on ts/core/MmlTree/MmlNodes/mo.ts
> +   * Determine of the mo consists of primes, and remap them if so.
typo.

2021-03-29 15:42 UTC, merged