Handle scaled table rows (for smallmatrix) properly in CHTML and SVG
mathjax/MathJax-src pull request #621
Opened 2021-03-12 13:22 UTC by dpvc

This PR fixes the `smallmatrix` environment by properly handling the scaled mrows so that the widths and separations are correct.  The problem was particularly apparent in SVG output, but also affected the separations in CHTML output.  In addition the colored backgrounds for cells and rows in SVG matrices were not always properly sized, and this fixes that as well.

2021-03-19 15:27 UTC, zorkow requested changes
Divisions are always expensive. I suggest to turn most of them into multiplications.

2021-03-19 15:27 UTC, zorkow commented on ts/output/svg/Wrappers/mtr.ts
> +        lLine: cLines[i] / scale, rLine: cLines[i + 1] / scale
A lot of division, that's expensive. Can we have `let scale = 1 / ...` and then multiply with `scale` instead?
I don't think that will introduce unwanted rounding errors.

2021-03-19 15:27 UTC, zorkow commented on ts/output/svg/Wrappers/mtr.ts
> +    const [dx, dy] = cell.placeCell(x + lSpace, y, w, h, d);
ditto.

2021-03-19 15:27 UTC, zorkow commented on ts/output/svg/Wrappers/mtr.ts
> +      const [H, D] = [this.H / scale, this.D / scale];
ditto.

2021-03-19 17:04 UTC, dpvc commented
> Divisions are always expensive. I suggest to turn most of them into multiplications.

Good idea.  Done.

2021-03-29 12:09 UTC, zorkow approved these changes
lgtm.

2021-03-29 15:14 UTC, merged