Modernize iterators
mathjax/MathJax-src pull request #626
Opened 2021-03-12 21:14 UTC by artagnon

Clean up some legacy code in the first patch, and modernize the LinkedList iterator in the second.

2021-03-19 17:59 UTC, dpvc requested changes
This looks good, but see my comment below.

2021-03-19 17:59 UTC, dpvc commented on ts/util/LinkedList.ts
> +   protected *reverse_iterator(): IterableIterator<DataClass> {
In MathJax, we use camelCase for function names, not underscores.  Can you change this to `reverseIterator`?

I'm also wondering if these need to be separate methods, or if they could be folded in the main functions.  E.g.:

``` javascript
 public reversed(): IterableIterator<DataClass> {
     return function * (): IterableIterator<DataClass> {
       let current = this.list;
       while (current.data !== END) {
         yield current.data as DataClass;
         current = current.prev;
       }
     }
   }
```

or even just

``` javascript
 public *reversed(): IterableIterator<DataClass> {
     let current = this.list;
     while (current.data !== END) {
       yield current.data as DataClass;
       current = current.prev;
     }
   }
```

I haven't tried these, but it seems unnecessary to have a method that just returns the result of another method.

2021-03-28 14:24 UTC, artagnon commented
Done; do check if it's alright.

2021-04-01 14:18 UTC, dpvc requested changes
Neither iterator works as expected (though the fix is easy).  I'm concerned, however, that this suggests that you didn't actually test the code to see if it works, as both iterators always return empty lists.  Did you test the code?  And if so, how?

2021-04-01 14:18 UTC, dpvc commented on ts/util/LinkedList.ts
>      let current = this.list;
This needs to be `this.list.next` not just `this.list`.  Th function as it stands never returns any values, as `this.list.data` is always `END`.

2021-04-01 17:42 UTC, artagnon commented
> Neither iterator works as expected (though the fix is easy). I'm concerned, however, that this suggests that you didn't actually test the code to see if it works, as both iterators always return empty lists. Did you test the code? And if so, how?

No, and I'm really clueless about how to test the change. Could you give me some pointers?

2021-04-01 18:02 UTC, dpvc commented
> I'm really clueless about how to test the change. Could you give me some pointers?

Here is a small program to test the iteration:

``` javascript
import {LinkedList} from './js/util/LinkedList';

const list = new LinkedList();

list.push('a', 'b', 'c');

console.log('The list is: ', Array.from(list));
console.log('Looping through the list:');

for (const item of list) {
  console.log(item);
}

console.log('The reversed list is: ', Array.from(list.reversed()));
console.log('Looping through the reversed list:');

for (const item of list.reversed()) {
  console.log(item);
}
```

run this using `node -r esm` and see that the output is as expected.  You should get:

```
The list is:  [ 'a', 'b', 'c' ]
Looping through the list:
a
b
c
The reversed list is:  [ 'c', 'b', 'a' ]
Looping through the reversed list:
c
b
a
```

2021-04-02 10:56 UTC, dpvc commented
Of course, you should also check an empty list, and a list with just one item as well.

2021-04-04 07:33 UTC, artagnon commented
Thanks; I can confirm that it works. Should we add automated tests?

2021-04-05 15:01 UTC, dpvc commented
> I can confirm that it works.

Excellent.

> Should we add automated tests?

We are working on a test framework, and there are already tests for much of the TeX input processing.  I had done some test for the `util` folder early on (in the `testsuite` branch), and I used those to test your code, but much more is needed, and those tests need to be converted to the framework used for the TeX input tests.

So for the moment, the answer is no.

2021-04-05 15:03 UTC, dpvc approved these changes
OK, the changes now look good.

2021-04-05 15:04 UTC, dpvc commented
I'm going to target this to 3.2.0, since the removal of the `toArray()` method is potentially a breaking change.

2021-05-12 16:55 UTC, merged